Homework 1 - [Xiaoshu Gui]
========================================================

### Task 1 - Implementation

<!--
Use this section to implement the fizzbuzz function.

This should include a short write up describing your approach
to implementing the function. Note that both code formating / style
and your writeup matter for your overall grade.
-->

```{r}
fizzbuzz = function(x){   # First Check whether the input is numeric
  if (any(!is.numeric(x))){ # If the input contains elements that are nonnumeric, the function will not return any result, but print oops.
    print("oops")}
    else {     # For inputs that are not multiples of 3 and 5, print the numbers on thier own
    for(i in x){  # use a for loop in case the input is a series of numbers instead of one.
    if (!isTRUE(any(i %% 3 == 0)) & !isTRUE(any(i %% 5 == 0))) # isTRUE solves the problem of NA
          print(i)
   else if(i %% 15 == 0)  # numbers which are both multiples of 3 and 5, implying that they are multiples of 3*5 = 15. Pirnt FizzBuzz.
      print("FizzBuzz")
   else if(i %% 3 == 0)  # numbers that are multiples of 3, print Fizz.
      print("Fizz")
   else if (i %% 5 == 0) # For numbers that are multiples of 5, print Buzz.
      print("Buzz")
  
   else print(i)
   }
}}
```

### Task 2 - Validation

<!--
Use this section to show the output of your 
fizzbuzz function for various inputs

No writeup is necessary for this section.
-->

```{r}
fizzbuzz(1)
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)

fizzbuzz(9:15)
fizzbuzz(15:9)

fizzbuzz(-1)
fizzbuzz(-3)
fizzbuzz(-5)

fizzbuzz(Inf)
fizzbuzz(-Inf)

fizzbuzz("A")
fizzbuzz(1.5)
fizzbuzz(1i)
fizzbuzz(4i)
```


